/**
 * @fileoverview added by tsickle
 * Generated from: compodoc/compodoc-schema.ts
 * @suppress {checkTypes,constantProperty,extraRequire,missingOverride,missingReturn,unusedPrivateMembers,uselessCode} checked by tsc
 */
/*!
 * Copyright 2019 VMware, Inc.
 * SPDX-License-Identifier: BSD-2-Clause
 */
/**
 * There are no typing definitions for the compodoc objects so we define them manually here.
 */
/**
 * The root object of the compodoc autogenerated documentation (documentation.json)
 * @record
 */
export function CompodocSchema() { }
if (false) {
    /** @type {?} */
    CompodocSchema.prototype.components;
}
/**
 * Component description as defined in the Compodoc generated documentation JSON
 * @record
 */
export function CompodocComponent() { }
if (false) {
    /** @type {?} */
    CompodocComponent.prototype.name;
    /** @type {?} */
    CompodocComponent.prototype.description;
    /** @type {?} */
    CompodocComponent.prototype.sourceCode;
    /** @type {?} */
    CompodocComponent.prototype.templateData;
    /** @type {?} */
    CompodocComponent.prototype.styleUrlsData;
    /** @type {?} */
    CompodocComponent.prototype.inputsClass;
    /** @type {?} */
    CompodocComponent.prototype.outputsClass;
}
/**
 * @record
 */
export function StyleUrlsData() { }
if (false) {
    /** @type {?} */
    StyleUrlsData.prototype.data;
}
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiY29tcG9kb2Mtc2NoZW1hLmpzIiwic291cmNlUm9vdCI6Im5nOi8vQHZjZC91aS1kb2MtbGliLyIsInNvdXJjZXMiOlsiY29tcG9kb2MvY29tcG9kb2Mtc2NoZW1hLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7Ozs7QUFjQSxvQ0FFQzs7O0lBREcsb0NBQWdDOzs7Ozs7QUFNcEMsdUNBUUM7OztJQVBHLGlDQUFhOztJQUNiLHdDQUFvQjs7SUFDcEIsdUNBQW1COztJQUNuQix5Q0FBcUI7O0lBQ3JCLDBDQUErQjs7SUFDL0Isd0NBQTZCOztJQUM3Qix5Q0FBOEI7Ozs7O0FBR2xDLG1DQUVDOzs7SUFERyw2QkFBYSIsInNvdXJjZXNDb250ZW50IjpbIi8qIVxuICogQ29weXJpZ2h0IDIwMTkgVk13YXJlLCBJbmMuXG4gKiBTUERYLUxpY2Vuc2UtSWRlbnRpZmllcjogQlNELTItQ2xhdXNlXG4gKi9cblxuLyoqXG4gKiBUaGVyZSBhcmUgbm8gdHlwaW5nIGRlZmluaXRpb25zIGZvciB0aGUgY29tcG9kb2Mgb2JqZWN0cyBzbyB3ZSBkZWZpbmUgdGhlbSBtYW51YWxseSBoZXJlLlxuICovXG5cbmltcG9ydCB7IEFwaVBhcmFtZXRlcnMgfSBmcm9tICcuLi9kb2N1bWVudGF0aW9uLXJldHJpZXZlci5zZXJ2aWNlJztcblxuLyoqXG4gKiBUaGUgcm9vdCBvYmplY3Qgb2YgdGhlIGNvbXBvZG9jIGF1dG9nZW5lcmF0ZWQgZG9jdW1lbnRhdGlvbiAoZG9jdW1lbnRhdGlvbi5qc29uKVxuICovXG5leHBvcnQgaW50ZXJmYWNlIENvbXBvZG9jU2NoZW1hIHtcbiAgICBjb21wb25lbnRzOiBDb21wb2RvY0NvbXBvbmVudFtdO1xufVxuXG4vKipcbiAqIENvbXBvbmVudCBkZXNjcmlwdGlvbiBhcyBkZWZpbmVkIGluIHRoZSBDb21wb2RvYyBnZW5lcmF0ZWQgZG9jdW1lbnRhdGlvbiBKU09OXG4gKi9cbmV4cG9ydCBpbnRlcmZhY2UgQ29tcG9kb2NDb21wb25lbnQge1xuICAgIG5hbWU6IHN0cmluZztcbiAgICBkZXNjcmlwdGlvbjogc3RyaW5nO1xuICAgIHNvdXJjZUNvZGU6IHN0cmluZztcbiAgICB0ZW1wbGF0ZURhdGE6IHN0cmluZztcbiAgICBzdHlsZVVybHNEYXRhOiBTdHlsZVVybHNEYXRhW107XG4gICAgaW5wdXRzQ2xhc3M6IEFwaVBhcmFtZXRlcnNbXTtcbiAgICBvdXRwdXRzQ2xhc3M6IEFwaVBhcmFtZXRlcnNbXTtcbn1cblxuZXhwb3J0IGludGVyZmFjZSBTdHlsZVVybHNEYXRhIHtcbiAgICBkYXRhOiBzdHJpbmc7XG59XG4iXX0=